### ISSUE TITLE
Fatal error with backend

### ISSUE THREAD

**Issue by funkyguy4000** [gregordr/ImageStore#32]
![image](https://user-images.githubusercontent.com/2363497/111238368-f4147e00-85c4-11eb-9aa2-b2556341f21e.png)

This is my docker-compose.yml file

```

version: "3.9"
services:
    nginx:
        image: imagestored/nginx
        ports:
            - "3000:8080" #Change to X:8080 to access on port X
        depends_on:
            - frontend

    frontend:
        image: imagestored/frontend
        depends_on:
            - backend

    backend:
        image: imagestored/backend
        restart: always
        environment:
            PGSTRING: postgres://postgres:example@db:5432/postgres # This string has to resolve to a Postgres database on version 11
        volumes:
            - ./media/:/code/media/
        depends_on:
            - db

    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data/:/var/lib/postgresql/data/

    # detectron2: # You can use either detectron2, which is slower but more accurate, or yolo, which is faster but has less accurate results, and is very leigthweight. Check yourself how much load detectron2 puts on your device, and if i$
    #     image: imagestored/detectron2
    #     environment:
    #         BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
    #         FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in seconds

    yolo:
        image: imagestored/yolo
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in seconds

```

I found this issue while googling around and was wondering if it happens to shed any light as to what is going on here? https://github.com/lovell/sharp/issues/2196

I am running this on Raspbian Buster on a Raspberry Pi 4 4GB model. I have a few other docker containers running along side this although I don't believe that should cause any issues.
Please let me know if you require any additional information
