### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by darrepac** [gregordr/ImageStore#35]
Using docker, I got the following errors:
`detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad3c6ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
`

Furthermore I have no picture shown. Is there something to do to trigger a scan? Or as I have 40k pictures, it takes time to do it?? (no message on backend)

Here is my yml file (I juste changed the port to 5000 to avoid conflict with other services running on the same server:
```
version: "3.9"
services:
    nginx:
        image: imagestored/nginx
        ports:
            - "5000:8080" #Change to X:8080 to access on port X
        depends_on:
            - frontend

    frontend:
        image: imagestored/frontend
        depends_on:
            - backend

    backend:
        image: imagestored/backend
        restart: always
        environment:
            PGSTRING: postgres://postgres:example@db:5432/postgres # This string has to resolve to a Postgres database on version 11
        volumes:
            - /home/pascal/Librephotos/pictures:/code/media/
        depends_on:
            - db

    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data/:/var/lib/postgresql/data/

    detectron2: # You can use either detectron2, which is slower but more accurate, or yolo, which is faster but has less accurate results, and is very leigthweight. Check yourself how much load detectron2 puts on your device, and if it's too much, switch to yolo. Comment out the model you want to use back in, but never comment out both.
        image: imagestored/detectron2
        environment:
            BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
            FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in seconds

    # yolo: # You can use either detectron2, which is slower but more accurate, or yolo, which is faster but has less accurate results, and is very leigthweight. Check yourself how much load detectron2 puts on your device, and if it's too much, switch to yolo. Comment out the model you want to use back in, but never comment out both.
    #     image: imagestored/yolo
    #     environment:
    #         BASE_ADDRESS: backend:4000 # Set this to the address the backend will be accessible on
    #         FETCH_INTERVAL: 10 # This is the interval the labeler will poll for new images in seconds

```

And the docker-compose output:
```

Attaching to imagestore_db_1, imagestore_detectron2_1, imagestore_backend_1, imagestore_frontend_1, imagestore_nginx_1
db_1          | The files belonging to this database system will be owned by user "postgres".
db_1          | This user must also own the server process.
db_1          |
detectron2_1  | ** fvcore version of PathManager will be deprecated soon. **
detectron2_1  | ** Please migrate to the version in iopath repo. **
detectron2_1  | https://github.com/facebookresearch/iopath
detectron2_1  |
db_1          | The database cluster will be initialized with locale "en_US.utf8".
db_1          | The default database encoding has accordingly been set to "UTF8".
db_1          | The default text search configuration will be set to "english".
db_1          |
db_1          | Data page checksums are disabled.
detectron2_1  | Config 'bottom-up-attention.pytorch/configs/bua-caffe/extract-bua-caffe-r101.yaml' has no VERSION. Assuming it to be compatible with latest v2.
db_1          |
detectron2_1  | ResNet.make_stage(first_stride=) is deprecated!  Use 'stride_per_block' or 'stride' instead.
detectron2_1  | ResNet.make_stage(first_stride=) is deprecated!  Use 'stride_per_block' or 'stride' instead.
db_1          | fixing permissions on existing directory /var/lib/postgresql/data ... ok
detectron2_1  | ResNet.make_stage(first_stride=) is deprecated!  Use 'stride_per_block' or 'stride' instead.
db_1          | creating subdirectories ... ok
db_1          | selecting default max_connections ... 100
db_1          | selecting default shared_buffers ... 128MB
db_1          | selecting default timezone ... Etc/UTC
db_1          | selecting dynamic shared memory implementation ... posix
db_1          | creating configuration files ... ok
db_1          | running bootstrap script ... ok
db_1          | performing post-bootstrap initialization ... ok
nginx_1       | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1       | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1       | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx_1       | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
nginx_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1       | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1       | /docker-entrypoint.sh: Configuration complete; ready for start up
db_1          | syncing data to disk ... ok
db_1          |
db_1          | Success. You can now start the database server using:
db_1          |
db_1          |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1          |
db_1          |
db_1          | WARNING: enabling "trust" authentication for local connections
db_1          | You can change this by editing pg_hba.conf or using the option -A, or
db_1          | --auth-local and --auth-host, the next time you run initdb.
db_1          | waiting for server to start....2021-04-03 18:07:29.683 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1          | 2021-04-03 18:07:30.206 UTC [48] LOG:  database system was shut down at 2021-04-03 18:07:14 UTC
db_1          | 2021-04-03 18:07:30.303 UTC [47] LOG:  database system is ready to accept connections
db_1          |  done
db_1          | server started
db_1          |
db_1          | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1          |
db_1          | 2021-04-03 18:07:31.732 UTC [47] LOG:  received fast shutdown request
db_1          | waiting for server to shut down....2021-04-03 18:07:31.798 UTC [47] LOG:  aborting any active transactions
db_1          | 2021-04-03 18:07:31.810 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db_1          | 2021-04-03 18:07:31.810 UTC [49] LOG:  shutting down
db_1          | 2021-04-03 18:07:32.268 UTC [47] LOG:  database system is shut down
db_1          |  done
db_1          | server stopped
db_1          |
db_1          | PostgreSQL init process complete; ready for start up.
db_1          |
db_1          | 2021-04-03 18:07:32.561 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1          | 2021-04-03 18:07:32.561 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1          | 2021-04-03 18:07:32.727 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1          | 2021-04-03 18:07:33.028 UTC [66] LOG:  database system was shut down at 2021-04-03 18:07:32 UTC
db_1          | 2021-04-03 18:07:33.108 UTC [1] LOG:  database system is ready to accept connections
backend_1     |
backend_1     | > photoproject@1.0.0 start
backend_1     | > npx ts-node --files ./src/index.ts
backend_1     |
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad3c6ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))
frontend_1    | INFO: Accepting connections at http://localhost:3000
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad2594f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad3fc970>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad3c6070>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad2e54c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad240af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad2d4a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad31fb20>: Failed to establish a new connection: [Errno 111] Connection refused'))
detectron2_1  | HTTPConnectionPool(host='backend', port=4000): Max retries exceeded with url: /labels/getBatch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4ad2bea60>: Failed to establish a new connection: [Errno 111] Connection refused'))
backend_1     | Listening on port 0.0.0.0:4000
backend_1     | Created Table media
backend_1     | Created Table albums
backend_1     | Created Table labelTable
backend_1     | Created Table album_photo
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:55 +0000] "GET / HTTP/1.1" 200 1496 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:55 +0000] "GET /static/css/main.eb694bcf.chunk.css HTTP/1.1" 200 887 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:55 +0000] "GET /static/css/2.0f1e8ff2.chunk.css HTTP/1.1" 200 11880 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:56 +0000] "GET /static/js/main.b803d491.chunk.js HTTP/1.1" 200 16057 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:56 +0000] "GET /static/js/2.c02ad7eb.chunk.js HTTP/1.1" 200 290041 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:56 +0000] "GET /favicon.ico HTTP/1.1" 200 3473 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:56 +0000] "GET /api/media/all HTTP/1.1" 200 2 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:29:56 +0000] "GET /api/albums/all HTTP/1.1" 200 2 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:30:00 +0000] "GET /api/albums/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/albums" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:30:02 +0000] "GET /api/media/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:30:02 +0000] "GET /api/albums/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:43:43 +0000] "GET /api/albums/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/albums" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:43:44 +0000] "GET /api/media/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
nginx_1       | 192.168.0.90 - - [03/Apr/2021:18:43:44 +0000] "GET /api/albums/all HTTP/1.1" 304 0 "http://192.168.0.25:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"

```
