### ISSUE TITLE
[Feature Request] Auto Import and Password Protection

### ISSUE THREAD

**Issue by imjoep** [gregordr/ImageStore#65]
Auto-import from directory.  I use Resilio-sync to auto-backup photos from my phone.  I would love the ability to have imagestore automatically import those files (or give me a command that I can run to do this myself).  

Second, I would like a basic username/password to protect my photos from being publicly available.

**Comment by gregordr** [comment]
Hey! Does resilio just put the files into some folder on your PC? If yes, it might be possible to just have an import volume now that I think about it :)

**Comment by imjoep** [comment]
Yes, resilio can just dump the files into a folder.  Any advice on how to create an import volume?

**Comment by imjoep** [comment]
If you can provide some guidance, I'd be happy to put in some time developing this feature.  I just don't know where to start.

**Comment by gregordr** [comment]
Hey, sorry for the long reply times! I'm currently abroad and have little access to the internet.

I have built an import Volume, but had little time to test it.

You can try it out by attaching 

```
    autoimport: # Automatic import of media in the "import" directory
        image: imagestored/autoimport:test
        restart: always
        environment:
            BACKEND_URL: backend:4000 # Set this to the address the backend will be accessible on
            SLEEP_TIME: 100 # How long to wait after each upload (ms)
            POLLING_RATE: 10000 # How often to check for new files (ms)
        depends_on:
            - backend
        volumes:
            - ./import/:/code/import
```

Let me know if it works, and especially if there are any issue or needs for improvement with it!
